### ISSUE TITLE
Not working with the Octobat API doc

### ISSUE THREAD

**Issue by KaKi87** [Irdis/SwDoc#14]
Hello,

First of all, thank you for creating this tool, which has been very helpful to me.

Today, I'm trying to convert the following API doc :

https://www.octobat.com/apidoc

https://raw.githubusercontent.com/0ctobat/openapi/master/dist/spec3.min.json

Even with *OpenAPI 3.0* checked, I still get the *Unable to generate document* error, whether I use the JSON link or copy/paste its content.

DevTools console doesn't display any errors.

Thanks

**Comment by Irdis** [comment]
Hi KaKi87
There are several issues with the structure of your spec. You can format your json and inspect errors with the document at https://editor.swagger.io/ 
Well there are quite few of them, but they are all similar, like duplicating operation ids, wrong declaration of path parameters etc.   If you struggle to fix them let me know. I'll take a deeper look.

**Comment by KaKi87** [comment]
I'll try, although this is quite annoying because it's actually not mine.

Thanks for your hints !
