### ISSUE TITLE
[requirement] support Simplified Chinese Characters

### ISSUE THREAD

**Issue by zzswang** [Irdis/SwDoc#49]
Hi, thanks for your excellent work, [swdoc.org](http://swdoc.org/), it’s a great tool.

Recently I use it to generate api pdf doc for printing.

But I found that some characters not show correctly, since I use Simplified Chinese Characters.

Could help to add some more fonts to support it?  I’m not familiar with #c.

Here is a free font:

https://github.com/adobe-fonts/source-han-sans

Thank you.

**Comment by Irdis** [comment]
Hi, added should be good to go.

**Comment by zzswang** [comment]
It worked, thanks.
